#!/usr/bin/env bash

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

NOTICE "... ... Starting Service test-service ... ..."

# A simple echo to show that this
# fake service is running
for i in `seq 1 25`
do
    NOTICE "[TEST-SERVICE] -- $i"
	sleep 1
done

# This simulate a crash
ERROR "[TEST-SERVICE] -- just crashed!"

# This exit code will be sent as the first parameter to the finish script
exit 1
