#!/usr/bin/env bash

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

NOTICE "[LOG-SERVICE] -- Ending Service log-service with parameters ${@}"

# This service will automaticaly restart after 3 secondes
sleep 3
