#!/usr/bin/env bash

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

NOTICE "[LOG-SERVICE] -- Starting Service log-service ..."

# A simple echo to show that this
# fake service is running
for i in `seq 1 10`
do
    NOTICE "[LOG-SERVICE] -- $i"
	sleep 1
done

# This simulate a crash
ERROR "[LOG-SERVICE] -- just crashed!"

# This exit code will be sent as the first parameter to the finish script
exit 1
