#!/usr/bin/env bash

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

NOTICE "[MAIN-SERVICE] -- Ending Service main-service with parameters ${@}"

# This is the main service.
# The container should stop whenever this service crash

# Tell runit to shutdown the system:
if [ "$1" = 1 ] && [ "$MAIN_RESTART" = 0 ]; then
    NOTICE "[MAIN-SERVICE] -- Stopping runit ..."
    runit stop &
fi
