#!/usr/bin/env bash

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

NOTICE "[MAIN-SERVICE] -- Starting Service main-service ..."

# A simple echo to show that this
# fake service is running
for i in `seq 1 600`
do
    NOTICE "[MAIN-SERVICE] -- $i - $(date) - Auto restart:$MAIN_RESTART"
	sleep 1
done

# This simulate a crash
ERROR "[MAIN-SERVICE] -- just crashed!"

# This exit code will be sent as the first parameter to the finish script
exit 1
