#!/bin/sh

echo "[MAIN-SERVICE] -- Starting Service main-service ..."

# A simple echo to show that this
# fake service is running
for i in `seq 1 600`
do
    echo "[MAIN-SERVICE] -- $i - " `date`
	sleep 1
done

# This simulate a crash
echo >&2 "[MAIN-SERVICE] -- just crashed!"

# This exit code will be sent as the first parameter to the finish script
exit 1
